"""Add tourism regime fields for Paraguay customers

Revision ID: 128177144df2
Revises: c72dfa0b3d92
Create Date: 2025-09-17 03:18:10.562227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128177144df2'
down_revision: Union[str, Sequence[str], None] = 'c72dfa0b3d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('tourism_regime', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('tourism_regime_pdf', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('tourism_regime_expiry', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'tourism_regime_expiry')
    op.drop_column('customers', 'tourism_regime_pdf')
    op.drop_column('customers', 'tourism_regime')
    # ### end Alembic commands ###
