"""add_currency_field_to_invoices

Revision ID: 4e9f6f26e197
Revises: eaf3cd424b38
Create Date: 2025-09-17 05:19:23.672630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9f6f26e197'
down_revision: Union[str, Sequence[str], None] = 'eaf3cd424b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add currency column as nullable first
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=True))
    
    # Update existing invoices to have default currency PYG
    op.execute("UPDATE invoices SET currency = 'PYG' WHERE currency IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('invoices', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency')
    # ### end Alembic commands ###
