"""Fix Paraguay fiscal fields and company settings

Revision ID: 6b40ae208cc4
Revises: 891f08c40066
Create Date: 2025-09-17 09:05:29.099460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b40ae208cc4'
down_revision: Union[str, Sequence[str], None] = '891f08c40066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('timbrado_fecha_vencimiento', sa.Date(), nullable=True, comment='Fecha de vencimiento del timbrado'))
    
    # Add iva_category with default value first
    op.add_column('invoice_lines', sa.Column('iva_category', sa.String(length=10), nullable=True, comment='Categoría IVA: 10, 5, EXENTO'))
    # Update existing records with default value
    op.execute("UPDATE invoice_lines SET iva_category = '10' WHERE iva_category IS NULL")
    # Make column NOT NULL after updating existing records
    op.alter_column('invoice_lines', 'iva_category', nullable=False)
    
    op.add_column('invoice_lines', sa.Column('iva_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monto de IVA de esta línea'))
    op.execute("UPDATE invoice_lines SET iva_amount = 0 WHERE iva_amount IS NULL")
    
    op.add_column('invoices', sa.Column('punto_expedicion', sa.String(length=10), nullable=True, comment='Punto de expedición (ej: 001)'))
    
    # Add condicion_venta with default value first
    op.add_column('invoices', sa.Column('condicion_venta', sa.String(length=20), nullable=True, comment='CONTADO o CREDITO'))
    op.execute("UPDATE invoices SET condicion_venta = 'CREDITO' WHERE condicion_venta IS NULL")
    op.alter_column('invoices', 'condicion_venta', nullable=False)
    
    op.add_column('invoices', sa.Column('lugar_emision', sa.String(length=100), nullable=True, comment='Ciudad de emisión de la factura'))
    op.add_column('invoices', sa.Column('subtotal_gravado_10', sa.Numeric(precision=12, scale=2), nullable=True, comment='Subtotal gravado al 10%'))
    op.execute("UPDATE invoices SET subtotal_gravado_10 = 0 WHERE subtotal_gravado_10 IS NULL")
    
    op.add_column('invoices', sa.Column('subtotal_gravado_5', sa.Numeric(precision=12, scale=2), nullable=True, comment='Subtotal gravado al 5%'))
    op.execute("UPDATE invoices SET subtotal_gravado_5 = 0 WHERE subtotal_gravado_5 IS NULL")
    
    op.add_column('invoices', sa.Column('subtotal_exento', sa.Numeric(precision=12, scale=2), nullable=True, comment='Subtotal exento de IVA'))
    op.execute("UPDATE invoices SET subtotal_exento = 0 WHERE subtotal_exento IS NULL")
    
    op.add_column('invoices', sa.Column('iva_10', sa.Numeric(precision=12, scale=2), nullable=True, comment='IVA 10%'))
    op.execute("UPDATE invoices SET iva_10 = 0 WHERE iva_10 IS NULL")
    
    op.add_column('invoices', sa.Column('iva_5', sa.Numeric(precision=12, scale=2), nullable=True, comment='IVA 5%'))
    op.execute("UPDATE invoices SET iva_5 = 0 WHERE iva_5 IS NULL")
    
    op.add_column('invoices', sa.Column('tourism_regime_applied', sa.Boolean(), nullable=True, comment='Se aplicó régimen turístico'))
    op.execute("UPDATE invoices SET tourism_regime_applied = false WHERE tourism_regime_applied IS NULL")
    
    op.add_column('invoices', sa.Column('tourism_regime_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Porcentaje de exención turística'))
    op.execute("UPDATE invoices SET tourism_regime_percentage = 0 WHERE tourism_regime_percentage IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tourism_regime_percentage')
    op.drop_column('invoices', 'tourism_regime_applied')
    op.drop_column('invoices', 'iva_5')
    op.drop_column('invoices', 'iva_10')
    op.drop_column('invoices', 'subtotal_exento')
    op.drop_column('invoices', 'subtotal_gravado_5')
    op.drop_column('invoices', 'subtotal_gravado_10')
    op.drop_column('invoices', 'lugar_emision')
    op.drop_column('invoices', 'condicion_venta')
    op.drop_column('invoices', 'punto_expedicion')
    op.drop_column('invoice_lines', 'iva_amount')
    op.drop_column('invoice_lines', 'iva_category')
    op.drop_column('company_settings', 'timbrado_fecha_vencimiento')
    # ### end Alembic commands ###
