"""add_company_settings_table

Revision ID: 891f08c40066
Revises: 4e9f6f26e197
Create Date: 2025-09-17 08:10:42.458934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891f08c40066'
down_revision: Union[str, Sequence[str], None] = '4e9f6f26e197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False, comment='Razón social de la empresa'),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True, comment='Nombre comercial'),
    sa.Column('ruc', sa.String(length=20), nullable=False, comment='RUC paraguayo (ej: 80012345-1)'),
    sa.Column('timbrado', sa.String(length=20), nullable=False, comment='Número de timbrado fiscal'),
    sa.Column('punto_expedicion', sa.String(length=10), nullable=False, comment='Punto de expedición'),
    sa.Column('dv_ruc', sa.String(length=2), nullable=True, comment='Dígito verificador del RUC'),
    sa.Column('direccion', sa.Text(), nullable=False, comment='Dirección completa de la empresa'),
    sa.Column('ciudad', sa.String(length=100), nullable=False, comment='Ciudad'),
    sa.Column('departamento', sa.String(length=100), nullable=False, comment='Departamento/Estado'),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True, comment='Código postal'),
    sa.Column('telefono', sa.String(length=20), nullable=True, comment='Teléfono fijo'),
    sa.Column('celular', sa.String(length=20), nullable=True, comment='Teléfono celular'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email principal'),
    sa.Column('sitio_web', sa.String(length=200), nullable=True, comment='Sitio web de la empresa'),
    sa.Column('moneda_defecto', postgresql.ENUM('PYG', 'USD', name='currency_type'), nullable=False, comment='Moneda por defecto'),
    sa.Column('iva_10_porciento', sa.Numeric(precision=5, scale=2), nullable=False, comment='Tasa IVA 10%'),
    sa.Column('iva_5_porciento', sa.Numeric(precision=5, scale=2), nullable=False, comment='Tasa IVA 5%'),
    sa.Column('iva_exento', sa.Boolean(), nullable=True, comment='Empresa exenta de IVA'),
    sa.Column('numeracion_facturas_inicio', sa.Integer(), nullable=False, comment='Número inicial de facturas'),
    sa.Column('numeracion_facturas_actual', sa.Integer(), nullable=False, comment='Número actual de facturas'),
    sa.Column('numeracion_cotizaciones_inicio', sa.Integer(), nullable=False, comment='Número inicial de cotizaciones'),
    sa.Column('numeracion_cotizaciones_actual', sa.Integer(), nullable=False, comment='Número actual de cotizaciones'),
    sa.Column('formato_impresion', postgresql.ENUM('A4', 'ticket', name='print_format'), nullable=False, comment='Formato de impresión por defecto'),
    sa.Column('logo_empresa', sa.String(length=500), nullable=True, comment='Path del logo de la empresa'),
    sa.Column('firma_digital', sa.String(length=500), nullable=True, comment='Path de la firma digital'),
    sa.Column('regimen_tributario', sa.String(length=50), nullable=False, comment='Régimen tributario'),
    sa.Column('contribuyente_iva', sa.Boolean(), nullable=False, comment='Es contribuyente de IVA'),
    sa.Column('actividad_economica', sa.String(length=200), nullable=True, comment='Actividad económica principal'),
    sa.Column('sector_economico', sa.String(length=100), nullable=True, comment='Sector económico'),
    sa.Column('notas_adicionales', sa.Text(), nullable=True, comment='Notas y observaciones adicionales'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuracion_completa', sa.Boolean(), nullable=False, comment='Indica si la configuración está completa'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
