"""add_can_create_customers_permission

Revision ID: ba585b231cdd
Revises: 6b40ae208cc4
Create Date: 2025-09-17 13:26:19.228744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba585b231cdd'
down_revision: Union[str, Sequence[str], None] = '6b40ae208cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_create_customers', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_customers')
    # ### end Alembic commands ###
