"""add_can_create_quotes_permission_to_users

Revision ID: c87db5e40a35
Revises: ba585b231cdd
Create Date: 2025-09-17 14:54:14.609840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87db5e40a35'
down_revision: Union[str, Sequence[str], None] = 'ba585b231cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_create_quotes', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_quotes')
    # ### end Alembic commands ###
