"""add_deposit_system_tables

Revision ID: eaf3cd424b38
Revises: 25372ebad3db
Create Date: 2025-09-17 05:12:48.232319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf3cd424b38'
down_revision: Union[str, Sequence[str], None] = '25372ebad3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_deposit_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_deposits_pyg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_deposits_pyg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applied_deposits_pyg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deposits_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_deposits_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applied_deposits_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('active_deposits_count', sa.Integer(), nullable=False),
    sa.Column('total_deposits_count', sa.Integer(), nullable=False),
    sa.Column('last_deposit_date', sa.Date(), nullable=True),
    sa.Column('last_application_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_deposit_summary_id'), 'customer_deposit_summary', ['id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deposit_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_reference', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_deposit_number'), 'deposits', ['deposit_number'], unique=True)
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.create_table('deposit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_applications_id'), 'deposit_applications', ['id'], unique=False)
    op.alter_column('users', 'can_manage_inventory',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_view_reports',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'can_manage_tourism_regime',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_manage_deposits',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_export_data',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'can_export_data',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_manage_deposits',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_manage_tourism_regime',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'can_view_reports',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'can_manage_inventory',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_deposit_applications_id'), table_name='deposit_applications')
    op.drop_table('deposit_applications')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_deposit_number'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_customer_deposit_summary_id'), table_name='customer_deposit_summary')
    op.drop_table('customer_deposit_summary')
    # ### end Alembic commands ###
